# Generated by Django 4.2 on 2023-05-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='oldPrice',
            field=models.FloatField(default=None, null=True),
        ),
    ]
