# Generated by Django 4.2 on 2023-05-05 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0002_course_oldprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dateCreated',
            field=models.DateField(default=datetime.datetime(2023, 5, 5, 21, 38, 15, 484959)),
        ),
    ]
